# Generated by Django 4.2.8 on 2023-12-30 13:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('contact', models.CharField(max_length=17, null=True)),
                ('role', models.CharField(blank=True, choices=[('D', 'Developer'), ('T', 'Tester'), ('', 'None'), ('A', 'Admin'), ('U', 'User')], max_length=2)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ctgryId', models.AutoField(primary_key=True, serialize=False)),
                ('ctgryName', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=100, verbose_name='Company Name')),
                ('companyAddr', models.TextField(max_length=300)),
                ('companyCntry', django_countries.fields.CountryField(max_length=2)),
                ('companyCntct', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter your mobile number in any format, it will be automatically formatted.', max_length=128, null=True, region=None, unique=True)),
                ('companyCode', models.CharField(error_messages={'null': "This field can't be null.", 'unique': 'Compnay with this code already exists ,Pleas try another!'}, help_text='A short code for company name', max_length=4, unique=True, verbose_name='Company Code')),
                ('companymobs', phonenumber_field.modelfields.PhoneNumberField(help_text='Add alternate contact number', max_length=128, null=True, region=None, unique=True)),
                ('companyMail', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('priority', models.CharField(max_length=30)),
                ('days', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('issued_on', models.DateTimeField(auto_now=True)),
                ('client', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=500, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('file', models.FileField(blank=True, help_text='Related to issue', null=True, upload_to='tickets')),
                ('expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=4)),
                ('approved_by', models.CharField(max_length=50)),
                ('approved_on', models.DateTimeField(auto_now=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('closed_by', models.CharField(max_length=50, null=True)),
                ('closed_on', models.DateTimeField(null=True)),
                ('old_ticket', models.BigIntegerField(null=True)),
                ('old_ticket_date', models.DateTimeField(null=True)),
                ('new_ticket', models.BigIntegerField(null=True)),
                ('new_ticket_date', models.DateTimeField(null=True)),
                ('dev_id', models.CharField(default='', max_length=50)),
                ('tester_id', models.CharField(default='', max_length=50)),
                ('dev_assigned_date', models.DateTimeField(null=True)),
                ('tester_assigned_date', models.DateTimeField(null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('rmrk_files', models.FileField(blank=True, help_text='Related to issue', null=True, upload_to='remarks')),
                ('tgt_days', models.IntegerField(blank=True, help_text='Target date', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cAdmin.category')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='maker', to=settings.AUTH_USER_MODEL, verbose_name='maker')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
        ),
        migrations.CreateModel(
            name='TicketLogs',
            fields=[
                ('ticket_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('issued_on', models.DateTimeField()),
                ('maker', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=10, null=True)),
                ('rmrk_files', models.FileField(blank=True, help_text='Related to issue', null=True, upload_to='remarks')),
                ('file', models.FileField(null=True, upload_to='tickets')),
                ('expiry', models.DateField(null=True)),
                ('status', models.CharField(max_length=4)),
                ('approved_by', models.CharField(max_length=50)),
                ('approved_on', models.DateTimeField(null=True)),
                ('updated_on', models.DateTimeField()),
                ('closed_by', models.CharField(max_length=50, null=True)),
                ('closed_on', models.DateTimeField(null=True)),
                ('old_ticket', models.BigIntegerField(null=True)),
                ('old_ticket_date', models.DateTimeField(null=True)),
                ('new_ticket', models.BigIntegerField(null=True)),
                ('new_ticket_date', models.DateTimeField(null=True)),
                ('dev_id', models.CharField(max_length=50)),
                ('tester_id', models.CharField(max_length=50)),
                ('dev_assigned_date', models.DateTimeField(null=True)),
                ('tester_assigned_date', models.DateTimeField(null=True)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cAdmin.category')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.AutoField(primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=30)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cAdmin.company')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cAdmin.company'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cAdmin.company'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cAdmin.department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='ticketlogs',
            constraint=models.UniqueConstraint(fields=('ticket_no', 'updated_on'), name='unique_combination'),
        ),
    ]
