# Generated by Django 4.2.8 on 2024-01-05 14:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyCntct',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Primary contact number is already in use.'}, help_text='Enter your mobile number in any format, it will be automatically formatted.', max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyMail',
            field=models.EmailField(error_messages={'unique': 'This mail id is already in use.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='companymobs',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Alternate Contact number is already in use.'}, help_text='Add alternate contact number', max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketlogs',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='file',
            field=models.FileField(blank=True, help_text='Related to issue', null=True, upload_to=''),
        ),
    ]
