# Generated by Django 4.2.8 on 2024-01-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cAdmin', '0002_alter_company_companycntct_alter_company_companymail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlogs',
            name='dev_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticketlogs',
            name='rmrk_files',
            field=models.FileField(blank=True, help_text='Related to issue', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ticketlogs',
            name='tester_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='dev_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='rmrk_files',
            field=models.FileField(blank=True, help_text='Related to issue', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tester_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
