# Generated by Django 4.2.8 on 2024-01-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cAdmin', '0004_alter_ticketlogs_dev_id_alter_ticketlogs_tester_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlogs',
            name='dev_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticketlogs',
            name='tester_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='dev_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='tester_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
