# Generated by Django 5.1 on 2024-10-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cAdmin', '0005_alter_ticketlogs_dev_id_alter_ticketlogs_tester_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='old_ticket',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
