# Generated by Django 5.1 on 2024-10-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cAdmin', '0006_alter_tickets_old_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlogs',
            name='old_ticket',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
