# Generated by Django 5.1 on 2025-01-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cAdmin', '0007_alter_ticketlogs_old_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='approved_on',
            field=models.DateTimeField(null=True),
        ),
    ]
