# Generated by Django 5.1 on 2025-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cAdmin', '0008_alter_tickets_approved_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='issued_on',
            field=models.DateTimeField(),
        ),
    ]
