# Generated by Django 5.1 on 2024-10-10 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cAdmin', '0005_alter_ticketlogs_dev_id_alter_ticketlogs_tester_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='uTickets',
            fields=[
                ('ticket_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('issued_on', models.DateTimeField(auto_now=True)),
                ('client', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=500, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10, null=True)),
                ('file', models.FileField(blank=True, help_text='Related to issue', null=True, upload_to='')),
                ('expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=4)),
                ('approved_by', models.CharField(max_length=50)),
                ('approved_on', models.DateTimeField(auto_now=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('closed_by', models.CharField(max_length=50, null=True)),
                ('closed_on', models.DateTimeField(null=True)),
                ('old_ticket', models.BigIntegerField(null=True)),
                ('old_ticket_date', models.DateTimeField(null=True)),
                ('new_ticket', models.BigIntegerField(null=True)),
                ('new_ticket_date', models.DateTimeField(null=True)),
                ('dev_id', models.CharField(default='', max_length=50, null=True)),
                ('tester_id', models.CharField(default='', max_length=50, null=True)),
                ('dev_assigned_date', models.DateTimeField(null=True)),
                ('tester_assigned_date', models.DateTimeField(null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('rmrk_files', models.FileField(blank=True, help_text='Related to issue', null=True, upload_to='')),
                ('tgt_days', models.IntegerField(blank=True, help_text='Target date', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cAdmin.category')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='umaker', to=settings.AUTH_USER_MODEL, verbose_name='maker')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
        ),
    ]
