# Generated by Django 5.1 on 2024-10-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utickets',
            name='old_ticket',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
