# Generated by Django 5.1 on 2025-02-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuser', '0003_alter_utickets_approved_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utickets',
            name='issued_on',
            field=models.DateTimeField(),
        ),
    ]
