# Generated by Django 4.2.6 on 2023-11-16 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tcktChat',
            fields=[
                ('msg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('msg', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ticket_no', models.CharField(max_length=15, null=bool)),
                ('seen_by', models.CharField(blank=True, max_length=150)),
                ('atchmnt', models.FileField(blank=True, null=True, upload_to='tickets')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
