# Generated by Django 5.1 on 2025-02-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcktchat',
            name='seen',
            field=models.IntegerField(default=0),
        ),
    ]
