# Generated by Django 5.1 on 2025-02-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_tcktchat_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcktchat',
            name='seen',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
